# Generated by Django 2.1.5 on 2019-05-06 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20190506_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'You are already subscribed to our news'}, max_length=30, unique=True),
        ),
    ]
