# Generated by Django 2.1.5 on 2019-05-07 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20190506_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='email', max_length=80, unique=True),
        ),
    ]
