# Generated by Django 2.1.5 on 2019-05-07 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isactive',
            field=models.BooleanField(default=False),
        ),
    ]
