# Generated by Django 2.1.5 on 2019-05-07 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_userfollowers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserFollowers',
            new_name='Follow',
        ),
    ]
