# Generated by Django 2.1.5 on 2019-05-07 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20190507_1001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('tweet_id', models.AutoField(primary_key=True, serialize=False)),
                ('tweet_content', models.CharField(max_length=280)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=280),
        ),
        migrations.AddField(
            model_name='tweet',
            name='tweeter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tweeter_profile', to='myapp.User'),
        ),
    ]
