# Generated by Django 2.1.5 on 2019-05-08 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20190507_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='TweetActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_id', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='tweet',
            name='num_likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tweetactivity',
            name='tweet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tweet', to='myapp.Tweet'),
        ),
    ]
