# Generated by Django 2.1.5 on 2019-05-09 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20190508_0730'),
    ]

    operations = [
        migrations.CreateModel(
            name='TweetReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_content', models.CharField(max_length=280)),
                ('replier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replier', to='myapp.User')),
                ('tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tweett', to='myapp.Tweet')),
            ],
        ),
    ]
